name: Build APK Trigger

on:
  issue_comment:
    types: [created]

jobs:
  pr_commented:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '!buildapk' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
